import type { IconProps } from 'nucleo-ui-essential-fill-duo-18'
import type { FC } from 'react'

export type AppIcon = FC<IconProps>

export {
  IconAlarmClockFillDuo18 as SleepIcon,
  IconArrowDoorOut3FillDuo18 as DisconnectIcon,
  IconBatteryHighFillDuo18 as BatteryIcon,
  IconBicycleFillDuo18 as BikeIcon,
  IconBoltLightningFillDuo18 as ActiveIcon,
  IconCalendarDaysFillDuo18 as CalendarIcon,
  IconChartBarTrendUpFillDuo18 as ActivityIcon,
  IconCheckFillDuo18 as CheckIcon,
  IconChevronDownFillDuo18 as ChevronDownIcon,
  IconChevronLeftFillDuo18 as ChevronLeftIcon,
  IconChevronRightFillDuo18 as ChevronRightIcon,
  IconChevronUpFillDuo18 as ChevronUpIcon,
  IconCircleInfoFillDuo18 as InfoIcon,
  IconCloudFillDuo18 as CloudIcon,
  IconDesktopArrowDownFillDuo18 as ExportIcon,
  IconFlameFillDuo18 as CaloriesIcon,
  IconGauge3FillDuo18 as GaugeIcon,
  IconGear2FillDuo18 as SettingsIcon,
  IconHeartFillDuo18 as HeartIcon,
  IconHotDrinkFillDuo18 as WaterIcon,
  IconHouse5FillDuo18 as TodayIcon,
  IconLayers3FillDuo18 as FloorsIcon,
  IconLeafFillDuo18 as BreathingIcon,
  IconLoaderFillDuo18 as LoaderIcon,
  IconMapFillDuo18 as DistanceIcon,
  IconMinusFillDuo18 as MinusIcon,
  IconPizzaSlice2FillDuo18 as NutritionIcon,
  IconRefresh2FillDuo18 as RefreshIcon,
  IconRoadmapFillDuo18 as RouteIcon,
  IconScaleFillDuo18 as BodyIcon,
  IconShieldCheckFillDuo18 as ShieldIcon,
  IconSignal2FillDuo18 as SignalIcon,
  IconSlidersFillDuo18 as MenuIcon,
  IconSparkle3FillDuo18 as SparkleIcon,
  IconSquareDottedArrowBottomRightFillDuo18 as ExternalIcon,
  IconStopwatchFillDuo18 as DurationIcon,
  IconTargetFillDuo18 as StepsIcon,
  IconUserFillDuo18 as UserIcon,
  IconWatchFillDuo18 as DeviceIcon,
  IconWindowChartLineFillDuo18 as TrendIcon,
  IconXmarkFillDuo18 as CloseIcon,
} from 'nucleo-ui-essential-fill-duo-18'
